### ISSUE TITLE
Hit indication

### ISSUE THREAD

**Issue by hi-names-nat** [Geeknerd1337/NSCM#45]
We need something to indicate the player has landed a shot. Such as blood in Half-Life. Flinching would be good too.

**Comment by Geeknerd1337** [comment]
This has now been added, but only to the degree that would be useful for ACT 1, in ACT 2 and beyond we should consider a system of overriding, changing, or giving each enemy a custom 'hit' particle. 

Flinching isn't out of the question, but I can't think of a good way to implement it other than what we already have. (Virus heads flinch when you shoot them)
